In [10]:
import tensorflow as tf

w=10
h=5

sess = tf.Session()

t_width = tf.range(w)
t_mtrx_x = tf.reshape(tf.tile(t_width, [h]), [1, h, w, 1, 1])
print(sess.run(t_mtrx_x))

t_height = tf.range(h)
t_mtrx_y = tf.reshape(tf.tile(t_height, [w]), [1, w, h, 1, 1])
print(sess.run(t_mtrx_y))




[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
